"""
Django settings for sangi_rcm project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cznpvl79v67$hc8m-f3zbqhv2+dydhn6#vq%6o7-(l%%k^6mnj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DEBUG = 'RENDER' not in os.environ  # False when live, True when local
ALLOWED_HOSTS = ['*'] # Allows Render to connect
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://bonita-rhinologic-censurably.ngrok-free.dev'
]


# Application definition

INSTALLED_APPS = [
    'jazzmin', # Must be before admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'attendance', # Our custom app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # 🟢 ADD THIS HERE!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sangi_rcm.urls'

TEMPLATES = [
{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / "templates"],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [

            'django.template.context_processors.debug',
            'django.template.context_processors.request',

            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',

        ],
    },
},
]

WSGI_APPLICATION = 'sangi_rcm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Uses Render's Postgres if live, SQLite if local
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py (At the bottom)

# The URL the browser uses to ask for the image
STATIC_URL = '/static/'

# Where your custom developer files live
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Where WhiteNoise collects them for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The WhiteNoise compression engine
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# ADD THESE TWO LINES FOR SELFIES:
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 🟢 Uses Cloudinary if live, Local folder if testing
if 'CLOUDINARY_URL' in os.environ:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

JAZZMIN_SETTINGS = {
    "site_title": "Sangi RCM Admin",
    "site_header": "Sangi RCM",
    "site_brand": "Director Portal",
    
    # 🟢 Pointing safely to your static/images/logo.png file
   "site_logo": "img/logo.png",  
    "login_logo": "img/logo.png",
    
    "welcome_sign": "Welcome to Sangi RCM Secure Portal",
    "copyright": "Sangi RCM Ltd",
    "show_ui_builder": False, 
}

JAZZMIN_UI_TWEAKS = {
    "theme": "litera", # Clean, modern, professional font/spacing
    
    # 🟢 Solid Blue Top Bar
    "navbar": "navbar-primary navbar-dark", 
    
    # 🟢 Bright White Sidebar with Blue active highlights
    "sidebar": "sidebar-light-primary", 
    
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "theme_color": "primary",
    
    # 🟢 This fixes the layout spacing
    "body_classes": "sidebar-mini", 
    
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
# Media files (user uploads)
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
