# Generated by Django 6.0.2 on 2026-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='master_faces/'),
        ),
    ]
