# Generated by Django 6.0.2 on 2026-02-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_edit_reason_attendance_is_hr_edited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('A', 'Absent'), ('H', 'Half Day'), ('W', 'Week-Off'), ('M', 'Missed Swap'), ('O', 'Official Holiday')], default='A', max_length=1),
        ),
    ]
