# Generated by Django 6.0.2 on 2026-03-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_companyholiday_attendance_employee_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
