# Generated by Django 6.0.2 on 2026-03-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_leaverequest_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(default='Unassigned', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='master_ids/'),
        ),
    ]
