# Generated by Django 6.0.2 on 2026-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('A', 'Absent'), ('H', 'Half Day'), ('W', 'Week-Off'), ('E', 'Early Leave'), ('M', 'Missed Swap'), ('O', 'Official Holiday')], default='A', max_length=1),
        ),
    ]
