# Generated by Django 6.0.2 on 2026-03-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_salary', models.DecimalField(decimal_places=2, help_text='The new salary requested by Accounts', max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending Admin Approval'), ('Approved', 'Approved & Applied'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_requests', to='attendance.employeeprofile')),
            ],
        ),
    ]
