# Generated by Django 6.0.2 on 2026-03-07 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_salaryupdaterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='e.g. Resignation - [Your Name]', max_length=200)),
                ('description', models.TextField(help_text='Detailed reason for resignation')),
                ('applied_date', models.DateField(default=django.utils.timezone.now, help_text='Date resignation was officially applied')),
                ('hr_status', models.CharField(choices=[('PENDING_HR', 'Pending HR Approval'), ('APPROVED_HR', 'Approved by HR (Pending Admin)'), ('REJECTED_HR', 'Rejected by HR'), ('APPROVED_ADMIN', 'Notice Period Active'), ('SHIFT_COMPLETED', 'Shift Completed (Inactive)')], default='PENDING_HR', max_length=20)),
                ('hr_rejection_reason', models.TextField(blank=True, help_text='Required if HR rejects', null=True)),
                ('hr_approved_on', models.DateTimeField(blank=True, null=True)),
                ('admin_status', models.CharField(choices=[('PENDING_HR', 'Pending HR Approval'), ('APPROVED_HR', 'Approved by HR (Pending Admin)'), ('REJECTED_HR', 'Rejected by HR'), ('APPROVED_ADMIN', 'Notice Period Active'), ('SHIFT_COMPLETED', 'Shift Completed (Inactive)')], default='PENDING_HR', max_length=20)),
                ('admin_approved_on', models.DateTimeField(blank=True, null=True)),
                ('notice_period_end_date', models.DateField(blank=True, help_text='Automatically calculated upon Admin Approval', null=True)),
                ('is_employee_inactive', models.BooleanField(default=False, help_text='System automatically sets to TRUE after notice period ends.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='attendance.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'is_employee_inactive')},
            },
        ),
    ]
