# Generated by Django 6.0.2 on 2026-03-09 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_resignationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], default='Savings', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='beneficiary_name',
            field=models.CharField(blank=True, help_text='Name exactly as per bank', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='uan_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PayrollUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposed_pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('proposed_bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('proposed_ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('proposed_uan_number', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Admin Approval'), ('Approved', 'Approved & Applied'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_requests', to='attendance.employeeprofile')),
            ],
        ),
    ]
