# Generated by Django 6.0.2 on 2026-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_employeeprofile_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='SANGI RCM', max_length=255)),
                ('company_account_no', models.CharField(help_text='Remitter Account Number (e.g., Company Bank A/C)', max_length=50)),
                ('company_account_type', models.CharField(default='Current', help_text='e.g., Current, Savings', max_length=50)),
                ('debit_account', models.CharField(help_text='Debit Account Number for the Annexure', max_length=50)),
            ],
            options={
                'verbose_name': 'Global Company Setting',
                'verbose_name_plural': 'Global Company Settings',
            },
        ),
    ]
