# Generated by Django 6.0.2 on 2026-03-09 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='employee_docs/photos/')),
                ('tenth_mark', models.FileField(blank=True, null=True, upload_to='employee_docs/10th/')),
                ('twelfth_mark', models.FileField(blank=True, null=True, upload_to='employee_docs/12th/')),
                ('graduation', models.FileField(blank=True, null=True, upload_to='employee_docs/graduation/')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/experience/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='employee_docs/pan/')),
                ('aadhaar_card', models.FileField(blank=True, null=True, upload_to='employee_docs/aadhaar/')),
                ('passbook', models.FileField(blank=True, null=True, upload_to='employee_docs/passbook/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='attendance.employeeprofile')),
            ],
        ),
    ]
