# Generated by Django 6.0.2 on 2026-03-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/aadhar/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pan_card_doc',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/pan/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='resume_cv',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/cvs/'),
        ),
    ]
