# Generated by Django 6.0.2 on 2026-03-11 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_employeeprofile_aadhar_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ref_post', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_organization', models.CharField(blank=True, max_length=150, null=True)),
                ('ref_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bgv_detail', to='attendance.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_audience', models.CharField(choices=[('All', 'All Employees'), ('Department', 'Specific Department'), ('Employee', 'Specific Employee')], default='All', max_length=50)),
                ('target_department', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_posted', to=settings.AUTH_USER_MODEL)),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DependentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relation', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='attendance.employeeprofile')),
            ],
        ),
    ]
