# Generated by Django 6.0.2 on 2026-03-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_backgroundverification_companynotice_dependentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationrequest',
            name='admin_status',
            field=models.CharField(choices=[('PENDING_HR', 'Pending HR Approval'), ('APPROVED_HR', 'Approved by HR (Pending Admin)'), ('REJECTED_HR', 'Rejected by HR'), ('APPROVED_ADMIN', 'Notice Period Active'), ('SHIFT_COMPLETED', 'Shift Completed (Inactive)'), ('REJECTED_ADMIN', 'Rejected by Admin')], default='PENDING_HR', max_length=20),
        ),
        migrations.AlterField(
            model_name='resignationrequest',
            name='hr_status',
            field=models.CharField(choices=[('PENDING_HR', 'Pending HR Approval'), ('APPROVED_HR', 'Approved by HR (Pending Admin)'), ('REJECTED_HR', 'Rejected by HR'), ('APPROVED_ADMIN', 'Notice Period Active'), ('SHIFT_COMPLETED', 'Shift Completed (Inactive)'), ('REJECTED_ADMIN', 'Rejected by Admin')], default='PENDING_HR', max_length=20),
        ),
    ]
