# Generated by Django 6.0.2 on 2026-03-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_resignationrequest_admin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='master_photo',
            field=models.ImageField(blank=True, null=True, upload_to='master_photos/'),
        ),
    ]
