# Generated by Django 6.0.2 on 2026-03-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_employeeprofile_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='experience_letter',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/exp/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='graduation',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/grad/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passbook',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/passbook/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tenth_mark',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/10th/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='twelfth_mark',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/12th/'),
        ),
    ]
