# Generated by Django 6.0.2 on 2026-03-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_method',
            field=models.CharField(blank=True, help_text='e.g., Face, Fingerprint, Card', max_length=50, null=True),
        ),
    ]
